### PR TITLE
v0.2.3 changelog and version increment

### PR DESCRIPTION
**Pull request by robacarp**

### CODE REVIEW

**Review by joshuap — APPROVED** [review]
🎉

**Comment by subzero10** [comment]
Hey @robacarp, have you considered using github actions to further automate the release script?

For example, you could come up with a workflow (that can be scheduled or dispatched manually) to execute the release script. We'd done something similar for the [js packages](https://github.com/honeybadger-io/honeybadger-js/actions/workflows/lerna-publish.yml). 
Note that only collaborators with write permissions on the repo can execute these workflows. If you like the idea, I can help with the implementation!

**Comment by robacarp** [comment]
@subzero10 I'm not opposed. The low frequency of releases here has felt like the payoff wouldn't be worth the investment. The script I added here is one I've copied over and over and over on dozens of projects, but I've never invested the time to actually tick the version numbers to match for a crystal project.

**Comment by subzero10** [comment]
I see. Then let's come back to this if we start releasing more frequently 👌

**Pull request merged**
